dist: trusty
language: cpp
compiler: clang

sudo: required

addons:
  apt:
    sources:
    - llvm-toolchain-trusty-5.0
    packages:
    - clang-5.0
    - cmake

script:
  - pwd
  - echo ${TRAVIS_BUILD_DIR}
  - echo ${SHELL}
  - export BUILD_DIR="${HOME}/build-work"
  - mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR}
  - cmake -DENABLE_COVERAGE=ON ${TRAVIS_BUILD_DIR}
  - cmake --build ./
  - sudo make install
  - src/cpt
  - llvm-profdata merge -sparse default.profraw -o default.profdata
  - llvm-cov show src/cpt -instr-profile=default.profdata
  - llvm-cov report src/cpt -instr-profile=default.profdata