dist: trusty
language: cpp
matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc

sudo: required

addons:
  apt:
    packages:
    - cmake

script:
  - pwd
  - echo ${TRAVIS_BUILD_DIR}
  - echo ${SHELL}
  - export BUILD_DIR=`realpath ~/build-work`
  - mkdir ${BUILD_DIR} && cd ${BUILD_DIR}
  - cmake ${TRAVIS_BUILD_DIR}
  - cmake --build ./