dist: trusty
language: cpp
matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc

sudo: required

addons:
  apt:
    packages:
    - cmake

script:
  - pwd
  - echo ${TRAVIS_BUILD_DIR}
  - cmake .
  - cmake --build ./