dist: trusty
language: cpp
compiler: clang

sudo: required

addons:
  apt:
    packages:
    - cmake

script:
  - pwd
  - echo ${TRAVIS_BUILD_DIR}
  - echo ${SHELL}
  - export BUILD_DIR="${HOME}/build-work"
  - mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR}
  - cmake -DENABLE_COVERAGE=ON ${TRAVIS_BUILD_DIR}
  - cmake --build ./